<?php 
/**
	Admin Page Framework v3.8.26 by Michael Uno 
	Generated by PHP Class Files Script Generator <https://github.com/michaeluno/PHP-Class-Files-Script-Generator>
	<http://en.michaeluno.jp/read-offline>
	Copyright (c) 2013-2021, Michael Uno; Licensed under MIT <http://opensource.org/licenses/MIT> */
class Read_Offline_AdminPageFramework_Form_View___CSS_term_meta extends Read_Offline_AdminPageFramework_Form_View___CSS_Base {
    protected function _get() {
        return $this->_getRules();
    }
    private function _getRules() {
        return ".read-offline-form-table-outer-row-term_meta,.read-offline-form-table-outer-row-term_meta > td {margin: 0;padding: 0;}.read-offline-form-table-term_meta > tbody > tr > td {margin-left: 0;padding-left: 0;}.read-offline-form-table-term_meta .read-offline-sectionset,.read-offline-form-table-term_meta .read-offline-section {margin-bottom: 0;}.read-offline-form-table-term_meta.add-new-term .title-colon {margin-left: 0.2em;}.read-offline-form-table-term_meta.add-new-term .read-offline-section .form-table > tbody > tr > td,.read-offline-form-table-term_meta.add-new-term .read-offline-section .form-table > tbody > tr > th{display: inline-block;width: 100%;padding: 0;float: right;clear: right;}.read-offline-form-table-term_meta.add-new-term .read-offline-field {width: auto;}.read-offline-form-table-term_meta.add-new-term .read-offline-field {max-width: 100%;}.read-offline-form-table-term_meta.add-new-term .sortable .read-offline-field {width: auto;} .read-offline-form-table-term_meta.add-new-term .read-offline-section .form-table > tbody > tr > th {font-size: 13px;line-height: 1.5;margin: 0;font-weight: 700;}.read-offline-form-table-term_meta .read-offline-section-title h3 {border: none;font-weight: bold;font-size: 1.12em;margin: 0;padding: 0;font-family: 'Open Sans', sans-serif; cursor: inherit; -webkit-user-select: inherit;-moz-user-select: inherit;user-select: inherit;}.read-offline-form-table-term_meta .read-offline-collapsible-title h3 {margin: 0;}.read-offline-form-table-term_meta h4 {margin: 1em 0;font-size: 1.04em;}.read-offline-form-table-term_meta .read-offline-section-tab h4 {margin: 0;} ";
    }
    }
    